import {
  Palette,
  Home,
  Wand2,
  Moon,
  Sun,
  Search,
  X,
  ArrowRight,
  ArrowUp,
  Check,
  SearchX,
  ShoppingBag,
  Monitor,
  Banknote,
  HeartPulse,
  Utensils,
  Plane,
  Building2,
  GraduationCap,
  ToyBrick,
  Shirt,
  Newspaper,
  Gamepad2,
  Dumbbell,
  type LucideIcon,
} from 'lucide-vue-next'

// kebab-case icon name -> Vue component (matches the `icon` field on palette presets)
export const ICONS: Record<string, LucideIcon> = {
  palette: Palette,
  home: Home,
  'wand-2': Wand2,
  moon: Moon,
  sun: Sun,
  search: Search,
  x: X,
  'arrow-right': ArrowRight,
  'arrow-up': ArrowUp,
  check: Check,
  'search-x': SearchX,
  'shopping-bag': ShoppingBag,
  monitor: Monitor,
  banknote: Banknote,
  'heart-pulse': HeartPulse,
  utensils: Utensils,
  plane: Plane,
  'building-2': Building2,
  'graduation-cap': GraduationCap,
  'toy-brick': ToyBrick,
  shirt: Shirt,
  newspaper: Newspaper,
  'gamepad-2': Gamepad2,
  dumbbell: Dumbbell,
}

export function icon(name: string): LucideIcon {
  return ICONS[name] ?? Palette
}
